# Generated by Django 3.0.6 on 2020-08-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='pics')),
                ('post', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('job', models.BooleanField(default=False)),
                ('breaking_news', models.BooleanField(default=False)),
                ('editorial', models.BooleanField(default=False)),
            ],
        ),
    ]
